name: 'rinha3-back-end-dotnet'

x-gateway-common: &gateway-common
  image: rinha-gateway:local
  pull_policy: never
  environment:
    - ASPNETCORE_URLS=http://0.0.0.0:8080
    - PP_DEFAULT_BASEURL=http://payment-processor-default:8080
    - PP_FALLBACK_BASEURL=http://payment-processor-fallback:8080
    - HTTP_TIMEOUT_MS=300
    - DB_CONNECTION_STRING=Host=/var/run/postgresql;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=10;Maximum Pool Size=30;Connection Pruning Interval=3;Max Auto Prepare=256;Auto Prepare Min Usages=2;No Reset On Close=true
  networks:
    - app-net
    - payment-processor
    - gateway-db-net
  volumes:
    - pg-socket:/var/run/postgresql:rw
  deploy:
    resources:
      limits:
        cpus: "0.60"
        memory: "100MB"

services:
  # Load balancer exposing port 9999
  lb:
    image: nginx:1.27-alpine
    container_name: rinha-lb
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway-1
      - gateway-2
    networks:
      - app-net
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "16MB"

  # Gateway instance 1 builds the image
  gateway-1:
    <<: *gateway-common
    container_name: rinha-gateway-1
    hostname: rinha-gateway-1
    build:
      context: ../src/rinha-gateway
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
        AOT: "true"
        TRIM: "true"
    depends_on:
      gateway-db:
        condition: service_started

  # Gateway instance 2 reuses the same local image
  gateway-2:
    <<: *gateway-common
    container_name: rinha-gateway-2
    hostname: rinha-gateway-2
    # No build here; uses image rinha-gateway:local
    depends_on:
      gateway-db:
        condition: service_started

  # Postgres for audit/summary consistency (low memory + socket)
  gateway-db:
    image: postgres:17-alpine
    container_name: rinha-gateway-db
    hostname: rinha-gateway-db
    command: >
      postgres
      -c checkpoint_timeout=600
      -c max_wal_size=4096
      -c synchronous_commit=0
      -c fsync=0
      -c full_page_writes=0
      -c shared_buffers=16MB
      -c effective_cache_size=64MB
      -c max_connections=60
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./../sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pg-data:/var/lib/postgresql/data
      - pg-socket:/var/run/postgresql
    networks:
      - gateway-db-net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "120MB"

networks:
  # External network created by the Payment Processors compose
  payment-processor:
    external: true
    name: payment-processor
  app-net:
    driver: bridge
  gateway-db-net:
    driver: bridge

volumes:
  pg-data:
  pg-socket: