@port=9999

### Basic health
GET http://localhost:{{port}}/healthz

### Create payment
POST http://localhost:{{port}}/payments
Content-Type: application/json
{
  "correlationId": "{{$guid}}",
  "amount": 19.90
}

### Summary (no filters)
GET http://localhost:{{port}}/payments-summary

### Summary with filters
GET http://localhost:{{port}}/payments-summary?from=2025-01-01T00:00:00Z&to=2025-12-31T23:59:59Z